import type { Plan } from '../types.ts';

export const DEFAULT_PLAN: Plan = {
  meta: {
    version: 'v9.1',
    name: 'Regreso al Gimnasio',
    gobernadores: [
      'Lumbar 2/10 → modificar · ≥4 → parar',
      'RIR autorregulación',
      'Cardio Z2 = talk test (no jadear)',
      'Sin intervalos máximos hasta tratar AOS',
      'NEAT: sem 1 medir baseline; luego +1500-2000 pasos/día',
    ],
  },
  phases: [
    { name: 'Reentrada', rir: '3–4', qs: [1] },
    { name: 'Construcción 1', rir: '2–3', qs: [2] },
    { name: 'Construcción 2', rir: '2', qs: [3] },
    { name: 'Densidad', rir: '1–2', qs: [4] },
    { name: 'Densidad + carries', rir: '1–2', qs: [5] },
    { name: 'Consolidar + retest', rir: '1', qs: [6] },
  ],
  challenges: [
    { q: 1, label: 'Plancha frontal', desc: 'Tiempo máximo en plancha frontal' },
    { q: 2, label: 'Flexiones', desc: 'Flexiones máximas en una serie' },
    { q: 3, label: 'Test bici 2 km', desc: 'Tiempo en bici 2 km ritmo constante' },
    { q: 4, label: 'Dominadas asistidas', desc: 'Reps con banda o máquina asistida' },
    { q: 5, label: 'Farmer carry', desc: 'Distancia máxima con carga fija' },
    { q: 6, label: 'RETEST', desc: 'Dominada estricta + flexiones + medición cintura y peso' },
  ],
  sessions: [
    {
      id: 'S1',
      name: 'Fuerza Base A',
      focus: 'Patrones primarios · series rectas',
      dur: 55,
      warmup: '5 min bici suave + 2 series de aproximación en Prensa 45° al 50% y 75% del peso de trabajo',
      ex: [
        { n: 'Prensa 45°', t: 'fuerza', sets: 3, rest: 120, tgt: '3×8 · arranque 110 kg', kg: 110 },
        { n: 'Press pecho máquina', t: 'fuerza', sets: 3, rest: 90, tgt: '3×8 · 48 kg', kg: 48 },
        { n: 'Jalón al pecho', t: 'fuerza', sets: 3, rest: 90, tgt: '3×8–10 · 46 kg', kg: 46 },
        { n: 'Hip thrust máquina', t: 'fuerza', sets: 3, rest: 90, tgt: '3×10 · 42 kg', kg: 42 },
        { n: 'Pallof press (anti-rotación)', t: 'fuerza', sets: 2, rest: 60, tgt: '2×10/lado · banda o polea' },
        { n: 'Finisher Z2 (opcional)', t: 'cardio', sets: 1, tgt: '8–10 min bici/caminata talk test · si vas <50 min' },
      ],
    },
    {
      id: 'S2',
      name: 'Potencia + Acarreos',
      focus: 'Bisagra potente · piernas · agarre · core',
      dur: 50,
      warmup: '5 min bici o remo suave + bisagra con palo 10 reps + 1 serie KB swing 8 kg',
      ex: [
        { n: 'KB swing (control)', t: 'fuerza', sets: 5, rest: 60, tgt: '5×8 · 12–16 kg · sin impacto lumbar', kg: 12 },
        { n: 'Step-up con carga', t: 'fuerza', sets: 3, rest: 90, tgt: '3×8/lado · mancuernas · autoregula' },
        { n: 'Press militar máquina', t: 'fuerza', sets: 3, rest: 90, tgt: '3×8 · 30 kg', kg: 30 },
        { n: 'Farmer carry', t: 'carry', sets: 3, tgt: '3×30 m · pesado · autoregula' },
        { n: 'Dead bug', t: 'mov', sets: 2, tgt: '2×10 · core anti-extensión · peso corporal' },
        { n: 'Finisher Z2 (opcional)', t: 'cardio', sets: 1, tgt: '8–10 min · si vas <50 min · talk test' },
      ],
    },
    {
      id: 'S3',
      name: 'Cardio Z2 + Movilidad',
      focus: 'Día fácil · talk test · ppm solo referencia',
      dur: 45,
      warmup: 'Los primeros 5 min del propio Z2 empezando muy suave',
      ex: [
        { n: 'Bici o remo Z2', t: 'cardio', sets: 1, tgt: '15→35 min · frase completa sin jadear' },
        { n: 'Movilidad cadera 90/90 + flexor', t: 'mov', sets: 1, tgt: '5 min' },
        { n: 'Movilidad torácica', t: 'mov', sets: 1, tgt: '3 min' },
        { n: 'Respiración diafragmática', t: 'mov', sets: 1, tgt: '2 min' },
        { n: 'Orofaríngeos (opcional · AOS)', t: 'mov', sets: 1, tgt: '5 min · coadyuvante · validar con médico' },
      ],
    },
    {
      id: 'S4',
      name: 'Fuerza Base B',
      focus: 'Empuje/tracción denso · superseries',
      dur: 55,
      warmup: '5 min bici suave + 1 serie aproximación remo máquina y press inclinado al 50%',
      ex: [
        { n: 'Remo máquina neutro (A1)', t: 'fuerza', sets: 3, rest: 90, tgt: '3×8 · 58 kg', kg: 58 },
        { n: 'Press pecho inclinado mancuerna (A2)', t: 'fuerza', sets: 3, rest: 90, tgt: '3×8 · autoregula' },
        { n: 'Face pull / jalón cerrado (B1)', t: 'fuerza', sets: 3, rest: 60, tgt: '3×12 · polea liviana' },
        { n: 'Elevaciones laterales (B2)', t: 'fuerza', sets: 3, rest: 60, tgt: '3×12 · 9 kg', kg: 9 },
        { n: 'Back extension (bisagra cadera)', t: 'fuerza', sets: 3, rest: 90, tgt: '3×12 · 55 kg', kg: 55 },
        { n: 'Suitcase carry (anti-flexión lat.)', t: 'carry', sets: 2, tgt: '2×30 m/lado · autoregula' },
        { n: 'Finisher Z2 (opcional)', t: 'cardio', sets: 1, tgt: '8–10 min · si vas <50 min · talk test' },
      ],
    },
    {
      id: 'S5',
      name: 'Densidad EMOM',
      focus: 'EMOM 16–20 min · cada minuto una estación',
      dur: 45,
      warmup: '5 min suave + 1 vuelta circuito a media carga',
      ex: [
        { n: 'Goblet squat (min 1)', t: 'fuerza', sets: 4, tgt: '×10 · 12–16 kg · registra en vueltas' },
        { n: 'Flexión en banda (min 2)', t: 'fuerza', sets: 4, tgt: '×8–12 · banda si falta fuerza' },
        { n: 'Remo mancuerna (min 3)', t: 'fuerza', sets: 4, tgt: '×10/lado · autoregula' },
        { n: 'KB swing (min 4)', t: 'fuerza', sets: 4, tgt: '×12 · 12–16 kg', kg: 12 },
        { n: 'Finisher Z2 (opcional)', t: 'cardio', sets: 1, tgt: '8–10 min · si vas <50 min · talk test' },
      ],
    },
    {
      id: 'S6',
      name: 'Cadena Posterior + Reintro',
      focus: 'Exposición graduada · gobernada por dolor 2/10',
      dur: 50,
      warmup: '5 min bici suave + gato-camello 10 reps + bisagra con palo 10 reps + goblet liviano 1×10',
      ex: [
        { n: 'Trap-bar (peso muerto hex.) Q2+', t: 'fuerza', sets: 3, rest: 120, tgt: '3×6 · muy ligero · Q1: usar goblet' },
        { n: 'Goblet squat profundo tempo 3-1-1', t: 'fuerza', sets: 3, rest: 90, tgt: '3×10 · 12–16 kg' },
        { n: 'Curl femoral prono', t: 'fuerza', sets: 3, rest: 90, tgt: '3×10 · 38 kg', kg: 38 },
        { n: 'RDL barra ligero técnico (Q2+)', t: 'fuerza', sets: 2, rest: 90, tgt: '2×10 · bisagra pura' },
        { n: 'Side plank', t: 'mov', sets: 2, tgt: '2×30 s/lado · peso corporal' },
      ],
    },
    {
      id: 'S7',
      name: 'Circuito Atlético + Reto',
      focus: '3–4 vueltas continuas · RPE 7–8 · sin máximos (AOS no tratada)',
      dur: 45,
      warmup: '5 min suave + 1 vuelta circuito a media intensidad',
      ex: [
        { n: 'Trineo / prensa explosiva ligera', t: 'circuit', sets: 1, tgt: '3–4 vueltas · 20 m / 12 reps · ligero' },
        { n: 'Battle rope / bici rápida', t: 'circuit', sets: 1, tgt: '20 s · RPE 7–8 · no sprint máximo' },
        { n: 'Med ball chest pass', t: 'circuit', sets: 1, tgt: '×10' },
        { n: 'Acarreo', t: 'carry', sets: 1, tgt: '30 m · autoregula' },
      ],
    },
  ],
};
